module.exports = {
  USER: "public/avatar",
  USER_IMAGE: "avatar",
  USER_THUMB: "public/avatar/thumb",
  USER_IMAGE_PATH: "userImage",
  USER_HEIGHT: 500,
  USER_WIDTH: 500,
  CATEGORY: "public/category",
  CATEGORY_IMAGE: "category",
  CATEGORY_THUMB: "public/category/thumb",
  CATEGORY_IMAGE_PATH: "categoryImage",
  CATEGORY_HEIGHT: 500,
  CATEGORY_WIDTH: 500,
  BLOG: "public/blog",
  BLOG_IMAGE: "blog",
  BLOG_THUMB: "public/blog/thumb",
  BLOG_IMAGE_PATH: "blogImage",
  BLOG_HEIGHT: 700,
  BLOG_WIDTH: 700,
  BANNER: "public/banner",
  BANNER_IMAGE: "banner",
  BANNER_THUMB: "public/banner/thumb",
  BANNER_IMAGE_PATH: "bannerImage",
  BANNER_HEIGHT: 700,
  BANNER_WIDTH: 700,
  PRODUCT: "public/product",
  PRODUCT_IMAGE: "product",
  PRODUCT_THUMB: "public/product/thumb",
  PRODUCT_IMAGE_PATH: "productImage",
  PRODUCT_HEIGHT: 500,
  PRODUCT_WIDTH: 500,
  METER: "public/meter",
  METER_IMAGE: "meter",
  METER_THUMB: "public/meter/thumb",
  METER_IMAGE_PATH: "meterImage",

  EXERCISE: "public/exercise",
  EXERCISE_IMAGE: "exercise",
  EXERCISE_IMAGE_PATH: "exerciseImage",

  METER_HEIGHT: 500,
  METER_WIDTH: 500,
  USER_DEFULTY_IMAGE: "static/user.svg",
  DEFAULT_IMAGE: "static/no_image.png",
  MAX_IMAGE_SIZE: 1,
  NodeMailertansport: {
    host: "smtp.gmail.com",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: "sugarmd.ph@gmail.com", // generated ethereal user
      pass: "anil@123", // generated ethereal password
    },
  },
};
